Aula 02 - Python \
Dados Numéricos


In [2]:
# Variável inteira
#print é utilizado para mostrar algo
a = 5
print('Valor de a = '+str(a))
type(a)

Valor de a = 5


int

In [3]:
# Variável dupla precisão
b = 5.0
print(b)
type(b)

5.0


float

In [4]:
# Converter float para int
# mudando as váriaveis 
c = int(b)
print(c)
type(c)

5


int

In [7]:
# Delacrando nan
import numpy as np
d = np.nan
print(d)
type(d)

nan


float

In [97]:
# Operação com NaN
e = d*5
print(e)
e = d+5
print(e)
e = np.nansum([d,5])
print(e)

nan
nan
5.0


## Dados de texto

In [101]:
# Declaração de variável texto
f = 'Sérgio'
g = "Strack"
print(f)
print(g)
print(f+g)
print(f+' '+g)

Sérgio
Strack
SérgioStrack
Sérgio Strack


## Dados tipo bool - lógica

In [102]:
# == é pra verificar a = b 
a == 5

True

In [103]:
h = (a==5)
print(h)
type(h)

True


bool

In [104]:
h = (a==5)
print(h)
type(h)

True


bool

In [15]:
i = True
type(i)

bool

In [16]:
# Retorna o tipo de dados da variáve
ii = 'True'
type(ii)

str

## Operação de Coparação

In [105]:
# Soma 
2+3

5

In [106]:
# Soma e atribui valor
ab = 7+9
print(ab)

16


In [109]:
# Multiplicação
l = a*b # Não use l como variável
print("Não use l como nome de variável")
j = 3*5
print(j)

Não use l como nome de variável
15


In [21]:
# Divisão
6/2

3.0

In [22]:
# Potencia
5**2

25

In [110]:
# Operações matemáticas com a bibliotéca math
import math

math.exp(100)

2.6881171418161356e+43

In [111]:
math.exp(9)

8103.083927575384

In [112]:
math.exp(8)

2980.9579870417283

In [114]:
math.exp(-1)

0.36787944117144233

In [115]:
#puxando a biblioteca
import math as mt
mt.log(73)

4.290459441148391

In [116]:
mt.log10(5)

0.6989700043360189

## Listas

In [117]:
myFirstList = [5,10,15]
print(myFirstList)

[5, 10, 15]


In [118]:
myFirstList==5

False

In [122]:
myFirstList[1]==a

False

In [123]:
mySecList = [5,a,'c']
print(mySecList)

[5, 5, 'c']


In [34]:
type(mySecList)

list

In [128]:
type(mySecList[2])

str

In [36]:
type(mySecList[1])

int

## Caminhos = Path

In [38]:
path = r"C:\Users\Win10\Documents\Python.atm\ENS410064-polui-o-atm-"
print(path)

C:\Users\Win10\Documents\Python.atm\ENS410064-polui-o-atm-


In [48]:
path = "C:\Users\Win10\Documents\Python.atm\ENS410064-polui-o-atm-"
print(path)

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (2057685505.py, line 1)

In [45]:
import os 
# Listar arquivos na pasta
os.listdir(path)

FileNotFoundError: [WinError 3] O sistema não pode encontrar o caminho especificado: 'C:/Users/Leonardo.Hoinaski/Documents/ENS410064_1'

In [50]:
# Selecionar primeiro arquivo listado
os.listdir(path)[3]

FileNotFoundError: [WinError 3] O sistema não pode encontrar o caminho especificado: 'C:/Users/Leonardo.Hoinaski/Documents/ENS410064_1'

In [51]:
# Concatenando caminhos
path+"/"+os.listdir(path)[0]

FileNotFoundError: [WinError 3] O sistema não pode encontrar o caminho especificado: 'C:/Users/Leonardo.Hoinaski/Documents/ENS410064_1'

In [52]:
# Listando caminho concatenado
os.listdir(path+"/"+os.listdir(path)[0])

FileNotFoundError: [WinError 3] O sistema não pode encontrar o caminho especificado: 'C:/Users/Leonardo.Hoinaski/Documents/ENS410064_1'

In [53]:
# Diretório que estou trababalhando
os.getcwd()

'C:\\Users\\Win10\\Documents\\Python.atm\\ENS410064-polui-o-atm-\\venv\\Scripts'

In [60]:
# Mudo de diretório para o caminho 
os.chdir('"C:\Users\Win10\Documents\"')

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 3-4: truncated \UXXXXXXXX escape (1416611338.py, line 2)

In [61]:
os.getcwd()

'C:\\Users\\Win10\\Documents\\Python.atm\\ENS410064-polui-o-atm-\\venv\\Scripts'

In [62]:
# Criando diretório
new_path = os.getcwd()+'/test'

if os.path.isdir(new_path):
    print('diretório já existe')
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)

Criando diretório C:\Users\Win10\Documents\Python.atm\ENS410064-polui-o-atm-\venv\Scripts/test


In [63]:
# Criando diretório
new_path = os.getcwd()+'/test2'

if os.path.isdir(new_path):
    print('diretório já existe')
    # Criando um arquivo de texto
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")

Criando diretório C:\Users\Win10\Documents\Python.atm\ENS410064-polui-o-atm-\venv\Scripts/test2


## Numpy arrays e Pandas DataFrames

In [64]:
import numpy as np
# Criando uma variável numpy
n = np.array(0)
type(n)

numpy.ndarray

In [66]:
# Criando uma variável numpy a partir de uma lista
myThirdList=[5,10,15,20,25,30]
n = np.array(myThirdList)
print(n)

[ 5 10 15 20 25 30]


In [68]:
# Criando uma matriz de 10x10 de números aleatórios entre 0 e 1
n = np.random.rand(5,5)
print(n)
# Dimensões da matrix
print(n.shape)

[[0.32768399 0.54265796 0.68247058 0.57076492 0.54904296]
 [0.99320821 0.08401097 0.24913379 0.32408801 0.71366736]
 [0.65372172 0.09173893 0.51923768 0.71460188 0.13694952]
 [0.97826642 0.61853954 0.63332463 0.23947415 0.93817108]
 [0.50029057 0.64498478 0.37717422 0.83764422 0.25864054]]
(5, 5)


In [73]:
# Acessando valores da matriz
n[3,:]

array([0.97826642, 0.61853954, 0.63332463, 0.23947415, 0.93817108])

In [74]:
n[:,3]

array([0.57076492, 0.32408801, 0.71460188, 0.23947415, 0.83764422])

In [76]:
n[:,3:4]

array([[0.57076492],
       [0.32408801],
       [0.71460188],
       [0.23947415],
       [0.83764422]])

In [78]:
n[0,3:4]

array([0.57076492])

In [85]:
n[0,-4]

0.5426579598236239

In [82]:
n[0,3:-1]

array([0.57076492])

In [87]:
n[0,2:]

array([0.68247058, 0.57076492, 0.54904296])

In [93]:
an = np.log(n*10)
print(an)

[[ 1.18687952  1.69130903  1.92054923  1.74180724  1.70300651]
 [ 2.29577013 -0.17422274  0.91281988  1.17584494  1.96524679]
 [ 1.87751158 -0.08622337  1.64719155  1.96655539  0.31444218]
 [ 2.28061186  1.82219093  1.84581295  0.87327528  2.23876214]
 [ 1.61001889  1.86405653  1.32753703  2.12542326  0.95026902]]
